// ─────────────────────────────────────────────────────────────────────────────
// SmartHealthAI — Hyderabad Hospital Dataset
// 25 hospitals with real coordinates, departments, and operational data
// ─────────────────────────────────────────────────────────────────────────────

export const HYDERABAD_HOSPITALS = [
  {
    id: "apollo-jubilee",
    name: "Apollo Hospitals Jubilee Hills",
    type: "Private",
    lat: 17.4239,
    lng: 78.4108,
    address: "Jubilee Hills, Hyderabad",
    departments: ["Cardiology", "Neurology", "Oncology", "Orthopedics", "General Medicine"],
    doctors: 68,
    emergencyBeds: 18,
    totalBeds: 710,
    waitTime: "22 min",
    queue: 14,
    rating: 4.8,
    phone: "040-23607777",
    accredited: true,
  },
  {
    id: "apollo-health-city",
    name: "Apollo Health City",
    type: "Private",
    lat: 17.3616,
    lng: 78.5466,
    address: "Gachibowli, Hyderabad",
    departments: ["Cardiology", "Transplant", "Oncology", "Neurology", "Pediatrics"],
    doctors: 120,
    emergencyBeds: 30,
    totalBeds: 1000,
    waitTime: "28 min",
    queue: 22,
    rating: 4.9,
    phone: "040-23607000",
    accredited: true,
  },
  {
    id: "yashoda-secunderabad",
    name: "Yashoda Hospitals Secunderabad",
    type: "Private",
    lat: 17.4399,
    lng: 78.4983,
    address: "Raj Bhavan Rd, Secunderabad",
    departments: ["Cardiology", "Neurology", "Orthopedics", "Gastroenterology", "General Medicine"],
    doctors: 55,
    emergencyBeds: 14,
    totalBeds: 600,
    waitTime: "18 min",
    queue: 10,
    rating: 4.7,
    phone: "040-44556600",
    accredited: true,
  },
  {
    id: "yashoda-somajiguda",
    name: "Yashoda Hospitals Somajiguda",
    type: "Private",
    lat: 17.4266,
    lng: 78.4543,
    address: "Somajiguda, Hyderabad",
    departments: ["Neurology", "Orthopedics", "Dermatology", "ENT", "General Medicine"],
    doctors: 48,
    emergencyBeds: 10,
    totalBeds: 430,
    waitTime: "15 min",
    queue: 8,
    rating: 4.6,
    phone: "040-44556000",
    accredited: true,
  },
  {
    id: "kims-secunderabad",
    name: "KIMS Hospital Secunderabad",
    type: "Private",
    lat: 17.4459,
    lng: 78.5037,
    address: "Minister Rd, Secunderabad",
    departments: ["Cardiology", "Pulmonology", "Orthopedics", "Urology", "General Medicine"],
    doctors: 62,
    emergencyBeds: 16,
    totalBeds: 650,
    waitTime: "25 min",
    queue: 18,
    rating: 4.7,
    phone: "040-44885000",
    accredited: true,
  },
  {
    id: "care-hospitals",
    name: "CARE Hospitals",
    type: "Private",
    lat: 17.3950,
    lng: 78.4867,
    address: "Nampally, Hyderabad",
    departments: ["Cardiology", "Neurology", "Orthopedics", "Oncology", "General Medicine"],
    doctors: 74,
    emergencyBeds: 20,
    totalBeds: 550,
    waitTime: "20 min",
    queue: 15,
    rating: 4.6,
    phone: "040-30418888",
    accredited: true,
  },
  {
    id: "aig-hospitals",
    name: "AIG Hospitals",
    type: "Private",
    lat: 17.4903,
    lng: 78.3816,
    address: "Mindspace, Gachibowli",
    departments: ["Gastroenterology", "Hepatology", "Bariatric Surgery", "General Medicine"],
    doctors: 40,
    emergencyBeds: 8,
    totalBeds: 350,
    waitTime: "12 min",
    queue: 6,
    rating: 4.8,
    phone: "040-42444222",
    accredited: true,
  },
  {
    id: "continental-hospital",
    name: "Continental Hospitals",
    type: "Private",
    lat: 17.4100,
    lng: 78.3467,
    address: "Tellapur, Hyderabad",
    departments: ["Cardiology", "Neurosurgery", "Orthopedics", "Oncology", "Pediatrics"],
    doctors: 55,
    emergencyBeds: 15,
    totalBeds: 600,
    waitTime: "18 min",
    queue: 12,
    rating: 4.5,
    phone: "040-67000167",
    accredited: true,
  },
  {
    id: "gandhi-hospital",
    name: "Gandhi Hospital",
    type: "Government",
    lat: 17.4497,
    lng: 78.4906,
    address: "Musheerabad, Hyderabad",
    departments: ["General Medicine", "Surgery", "Orthopedics", "Gynecology", "Pediatrics"],
    doctors: 110,
    emergencyBeds: 35,
    totalBeds: 1200,
    waitTime: "45 min",
    queue: 40,
    rating: 3.8,
    phone: "040-27505566",
    accredited: false,
  },
  {
    id: "osmania-hospital",
    name: "Osmania General Hospital",
    type: "Government",
    lat: 17.3853,
    lng: 78.4731,
    address: "Afzalgunj, Hyderabad",
    departments: ["General Medicine", "Surgery", "ENT", "Dermatology", "Psychiatry"],
    doctors: 130,
    emergencyBeds: 40,
    totalBeds: 1400,
    waitTime: "55 min",
    queue: 52,
    rating: 3.6,
    phone: "040-24600019",
    accredited: false,
  },
  {
    id: "nims",
    name: "NIMS (Nizams Institute of Medical Sciences)",
    type: "Government",
    lat: 17.3951,
    lng: 78.4564,
    address: "Punjagutta, Hyderabad",
    departments: ["Neurology", "Neurosurgery", "Cardiology", "Oncology", "General Medicine"],
    doctors: 95,
    emergencyBeds: 28,
    totalBeds: 900,
    waitTime: "38 min",
    queue: 32,
    rating: 4.0,
    phone: "040-23489000",
    accredited: true,
  },
  {
    id: "tims",
    name: "TIMS (Telangana Institute of Medical Sciences)",
    type: "Government",
    lat: 17.4947,
    lng: 78.3543,
    address: "Gachibowli, Hyderabad",
    departments: ["General Medicine", "Surgery", "Orthopedics", "Gynecology", "Pediatrics"],
    doctors: 70,
    emergencyBeds: 20,
    totalBeds: 700,
    waitTime: "42 min",
    queue: 35,
    rating: 3.9,
    phone: "040-23118888",
    accredited: false,
  },
  {
    id: "star-hospital",
    name: "Star Hospitals",
    type: "Private",
    lat: 17.4040,
    lng: 78.4477,
    address: "Banjara Hills, Hyderabad",
    departments: ["Cardiology", "Neurology", "Orthopedics", "ENT", "General Medicine"],
    doctors: 45,
    emergencyBeds: 12,
    totalBeds: 400,
    waitTime: "20 min",
    queue: 11,
    rating: 4.4,
    phone: "040-44777999",
    accredited: true,
  },
  {
    id: "omega-hospital",
    name: "Omega Hospital",
    type: "Private",
    lat: 17.4303,
    lng: 78.3906,
    address: "Madhapur, Hyderabad",
    departments: ["Oncology", "Bone Marrow Transplant", "Hematology"],
    doctors: 30,
    emergencyBeds: 6,
    totalBeds: 200,
    waitTime: "16 min",
    queue: 5,
    rating: 4.6,
    phone: "040-23560777",
    accredited: true,
  },
  {
    id: "sunshine-hospital",
    name: "Sunshine Hospitals",
    type: "Private",
    lat: 17.4388,
    lng: 78.4052,
    address: "Begumpet, Hyderabad",
    departments: ["Orthopedics", "Sports Medicine", "Physiotherapy", "General Surgery"],
    doctors: 35,
    emergencyBeds: 8,
    totalBeds: 280,
    waitTime: "14 min",
    queue: 7,
    rating: 4.5,
    phone: "040-44655000",
    accredited: true,
  },
  {
    id: "maxcure-hospital",
    name: "Maxcure Hospital",
    type: "Private",
    lat: 17.4235,
    lng: 78.4485,
    address: "Hitech City, Hyderabad",
    departments: ["Cardiology", "Neurology", "Gastroenterology", "Pediatrics"],
    doctors: 42,
    emergencyBeds: 10,
    totalBeds: 320,
    waitTime: "19 min",
    queue: 9,
    rating: 4.3,
    phone: "040-48486868",
    accredited: true,
  },
  {
    id: "citizens-hospital",
    name: "Citizens Specialty Hospital",
    type: "Private",
    lat: 17.4067,
    lng: 78.5517,
    address: "Nallagandla, Hyderabad",
    departments: ["Cardiology", "Neurology", "Orthopedics", "Oncology", "Renal"],
    doctors: 50,
    emergencyBeds: 12,
    totalBeds: 350,
    waitTime: "22 min",
    queue: 13,
    rating: 4.4,
    phone: "040-67191919",
    accredited: true,
  },
  {
    id: "medicover-hospital",
    name: "Medicover Hospitals",
    type: "Private",
    lat: 17.4419,
    lng: 78.3870,
    address: "Hitech City, Hyderabad",
    departments: ["Cardiology", "Orthopedics", "Dermatology", "General Medicine", "ENT"],
    doctors: 38,
    emergencyBeds: 8,
    totalBeds: 260,
    waitTime: "13 min",
    queue: 6,
    rating: 4.2,
    phone: "040-68888888",
    accredited: true,
  },
  {
    id: "tulip-hospital",
    name: "Tulip Hospital",
    type: "Private",
    lat: 17.4527,
    lng: 78.3769,
    address: "Kondapur, Hyderabad",
    departments: ["Pediatrics", "Neonatology", "Gynecology", "General Medicine"],
    doctors: 28,
    emergencyBeds: 6,
    totalBeds: 180,
    waitTime: "10 min",
    queue: 4,
    rating: 4.3,
    phone: "040-40150000",
    accredited: true,
  },
  {
    id: "rainbow-hospital",
    name: "Rainbow Children's Hospital",
    type: "Private",
    lat: 17.4315,
    lng: 78.4130,
    address: "Banjara Hills, Hyderabad",
    departments: ["Pediatrics", "Neonatology", "Pediatric Surgery", "Pediatric Neurology"],
    doctors: 52,
    emergencyBeds: 14,
    totalBeds: 340,
    waitTime: "17 min",
    queue: 8,
    rating: 4.7,
    phone: "040-44447777",
    accredited: true,
  },
  {
    id: "secunderabad-govt",
    name: "Government District Hospital Secunderabad",
    type: "Government",
    lat: 17.4499,
    lng: 78.5067,
    address: "Patny, Secunderabad",
    departments: ["General Medicine", "Surgery", "Gynecology", "ENT"],
    doctors: 45,
    emergencyBeds: 15,
    totalBeds: 400,
    waitTime: "50 min",
    queue: 38,
    rating: 3.5,
    phone: "040-27803145",
    accredited: false,
  },
  {
    id: "govt-maternity",
    name: "Govt. Maternity Hospital Hyderabad",
    type: "Government",
    lat: 17.3814,
    lng: 78.4690,
    address: "Petlaburj, Hyderabad",
    departments: ["Gynecology", "Obstetrics", "Neonatology", "Pediatrics"],
    doctors: 40,
    emergencyBeds: 12,
    totalBeds: 300,
    waitTime: "35 min",
    queue: 28,
    rating: 3.7,
    phone: "040-24563541",
    accredited: false,
  },
  {
    id: "basavatarakam",
    name: "Basavatarakam Indo-American Cancer Hospital",
    type: "Private",
    lat: 17.4190,
    lng: 78.3984,
    address: "Banjara Hills, Hyderabad",
    departments: ["Oncology", "Radiation Therapy", "Surgical Oncology", "Palliative Care"],
    doctors: 36,
    emergencyBeds: 6,
    totalBeds: 240,
    waitTime: "25 min",
    queue: 10,
    rating: 4.6,
    phone: "040-23551235",
    accredited: true,
  },
  {
    id: "global-hospital",
    name: "Global Hospitals",
    type: "Private",
    lat: 17.3892,
    lng: 78.4538,
    address: "Lakdi ka Pul, Hyderabad",
    departments: ["Transplant", "Hepatology", "Nephrology", "Cardiology", "Neurology"],
    doctors: 58,
    emergencyBeds: 16,
    totalBeds: 500,
    waitTime: "24 min",
    queue: 14,
    rating: 4.5,
    phone: "040-30244444",
    accredited: true,
  },
  {
    id: "lvpei",
    name: "L V Prasad Eye Institute",
    type: "Private",
    lat: 17.4263,
    lng: 78.4358,
    address: "Banjara Hills, Hyderabad",
    departments: ["Ophthalmology", "Retina", "Cornea", "Glaucoma", "Pediatric Ophthalmology"],
    doctors: 60,
    emergencyBeds: 8,
    totalBeds: 280,
    waitTime: "20 min",
    queue: 15,
    rating: 4.9,
    phone: "040-30612525",
    accredited: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Helper: calculate distance between two lat/lng points (Haversine formula)
// Returns distance in kilometers
// ─────────────────────────────────────────────────────────────────────────────
export function getDistance(lat1, lng1, lat2, lng2) {
  const R = 6371;
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) * Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper: get estimated travel time from distance (assume 30km/h city speed)
// ─────────────────────────────────────────────────────────────────────────────
export function getTravelTime(distKm) {
  const minutes = Math.round((distKm / 30) * 60);
  return `${minutes} min`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper: get sorted hospitals by distance from a user location
// Also computes AI recommendation score
// ─────────────────────────────────────────────────────────────────────────────
export function getNearbyHospitals(userLat, userLng, department = "", limit = 25) {
  return HYDERABAD_HOSPITALS
    .map((h) => {
      const dist = getDistance(userLat, userLng, h.lat, h.lng);
      const hasDept = department
        ? h.departments.some((d) => d.toLowerCase().includes(department.toLowerCase()))
        : true;
      // AI score: lower wait + closer distance + dept match + beds available
      const score =
        (hasDept ? 30 : 0) +
        Math.max(0, 20 - h.queue) +
        Math.max(0, 20 - Math.round(dist)) +
        h.emergencyBeds * 0.5;
      return {
        ...h,
        distance: dist,
        distanceLabel: `${dist.toFixed(1)} km`,
        travelTime: getTravelTime(dist),
        aiScore: score,
        hasDepartment: hasDept,
      };
    })
    .sort((a, b) => a.distance - b.distance)
    .slice(0, limit)
    .sort((a, b) => b.aiScore - a.aiScore); // Re-sort by AI score after distance filter
}
